/********************************************************************************************* 
Version                         Date                           Name             Description
**********************************************************************************************
*V1.0                          20-06-2022                      Developer1         Add Method Implemented
*************************************************************************************************/
public with sharing class Calculator {
    public Calculator() {

    }
    public integer add(integer a,integer b)
    {
        return a+b;
    }  
}
